# Generated by Django 4.1.2 on 2022-10-21 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0004_alter_pet_slug'),
    ]

    operations = ()
