# Generated by Django 4.1.2 on 2022-10-22 07:58

from django.db import migrations, models
import petstagram.basic.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='mediafiles/pet_photo/', validators=[petstagram.basic.validators.validate_image_less_than_5mgb]),
        ),
    ]
