# Generated by Django 4.1.2 on 2022-10-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0004_alter_photo_photo'),
    ]

    operations = []
