# Generated by Django 4.1.2 on 2022-10-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_create_photo_like_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
