# Generated by Django 4.1.2 on 2022-10-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
